#pragma once

#define G 9.8
#define DEFAULT_SEA_RHO 1.225

#define DEFAULT_MASS 80 
#define DEFAULT_CRR 0.004
#define DEFAULT_CDA_TT 0.22
#define DEFAULT_CDA_OOS 0.4
#define DEFAULT_POWER_OOS 500
#define DEFAULT_FORCE_BRAKING 200
#define DEFAULT_BANKANGLE 30
#define DEFAULT_EFFICIENCY 0.97